apiVersion: v1
data:
  values.yaml: ENC[AES256_GCM,data:2sEagCHnvOyHc4qogXJq5LZUPH/mP2AFcv9benHg0j1kU12VO+YWKhHms/+bsvNCtGbZU08RIT/j6zoKqvkqzbkAqkEgbIISLMoQF6mKW/zyWHUpFmEP/ms6wwec9gqrWC1MuJq5B0audnxM1Lzy95Z48iRSb6U2bheKLDkBKfeSaAoqoi484APjmBtaZozjt71mNSN1g/r6cAy0GK1UerT/+D1RmDcKcfszpa+mpFaoK0YrT8ZFQ4O9zPZECr+o4OSd4TDFspjjdUOPv9P/x6+1uBmLeSOeZ8V3lfa4a6jnfl8crpQ/JYbzpEmGBPTXl31F0YhINw==,iv:wLtAHdXbZylrhEYK0dHHVM3G1FhrCWYqoBI7d6hR+iE=,tag:Bn4z4LSX6Z/UJSswBnZgwA==,type:str]
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-stack-helmrelease
  namespace: monitoring
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  lastmodified: "2021-03-21T22:42:15Z"
  mac: ENC[AES256_GCM,data:NoMFrGRWpRfNQeqWV6uvqFDjnSuJYpLeOieDQDLQK2ZbIcdrWXzw5tD3HCc2AERB3xUY8Ux103bnvM9/pJdzmr29ipzw93MDaCRYQO5Z5YkCHbb2I2OJy3lsC7baDCx/LL+vd6HXL5EE7/nkJMhE83IEK/byFpgQzY799xC7zo8=,iv:TKtBXA4L5QCrK9+yfWNg/gS3gKDsYuQjIzYoKYsLp2I=,tag:jB/lWo0PgdFZQEV/EVUE4Q==,type:str]
  pgp:
    - created_at: "2021-03-21T22:42:14Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQGMA/JorPHm1g9XAQv9HlHo7jlt6UUPVb2e4d22vb+CzlTgQWyCjixrZ5nzldAC
        l25AYPErfCeDxmqdlwrAvmUcpeES54gu69F3j0uVd0OT9cksXn7mWmS/dWxyQYiX
        YnEK/gTgHLhfNS6dmdo1PzcKXrg28sDrUYMhz+UmNropqUjBsiCqf6uTMOW/4Noa
        4IzIh8s/pho7HDz/OYezozYXRXYWRNyp+OQBMjg4aPzVAaEVD81xIRlWTg/5NcSy
        PYWkvGy7oubJXGaLOWkVAq73bOjYFhGq1v02aFwV8JmAzSSVCC3pDJPwpXOukEKG
        RgupRjkSIJTm1CmtBH/6nS0jWET+dJ3SXKeeOkCT1djcml9zfd7okPNVI8wMjLtJ
        tn9FERuu+tsExUOb7vgiHyfXAT9yxW/AlhLYI4VBYpjXkAy2HVYYmAcdA/rHgC17
        Azg6PqtkmGcKihbkzOzuMEhVGF1tYIczOFmpCuSfDN7MtVlH/c5Bu4vy6BtTOqSZ
        jK2NZYLNk5I15xb72rlC0l4B6faTEmnDrTWePQP2xT0TugBRHKNtdrvLL4HLTBxT
        Hw8h11+x6As+qcvwy28fVvwDCj5eOGX5IrDPoRcf+nlGwS9kqeeewtn70WP+yOGm
        XhlqEOfrZFw3Jy6XBZ24
        =U2qu
        -----END PGP MESSAGE-----
      fp: C8F8A49D04A1AB639F8EA21CDBA4B1DCB1FA5BDD
  encrypted_regex: ^(data|stringData)$
  version: 3.6.1
