---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: bazarr
      version: 8.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: ghcr.io/k8s-at-home/bazarr
      tag: v0.9.4
      pullPolicy: IfNotPresent
    env:
      TZ: "Europe/Paris"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config
    additionalVolumeMounts:
      - name: nfs-video-media
        mountPath: "/mnt/storage/video"
    additionalVolumes:
      - name: nfs-video-media
        persistentVolumeClaim:
          claimName: nfs-video-media
    service:
      annotations:
        prometheus.io/probe: "true"
        prometheus.io/protocol: http
    resources:
      requests:
        memory: 500Mi
        cpu: 500m
      limits:
        memory: 1500Mi
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/auth-url: "http://authelia.networking.svc.cluster.local/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://login.${SECRET_CLUSTER_DOMAIN}/"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header Accept-Encoding "";
          sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://gilbn.github.io/theme.park/CSS/themes/bazarr/space-gray.css"></head>';
          sub_filter_once on;
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/appName: "Bazarr"
        forecastle.stakater.com/icon: "https://raw.githubusercontent.com/morpheus65535/bazarr/master/static/logo128.png"
        forecastle.stakater.com/network-restricted: "true"
      hosts:
        - host: bazarr.${SECRET_CLUSTER_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "bazarr.${SECRET_CLUSTER_DOMAIN}"
