apiVersion: v1
data:
  values.yaml: ENC[AES256_GCM,data:Bf+98XqxMk2WKKTcQU/6m9WptOtI+NXDgqKctP/614KM5t+I1rThrlkIVLA2aa7oButDRyPIHPVRfE/2xebjrqSxqvYspYsMm3UpEPMFaJxyMah+spOmuuDZXiAikmGhvLJEl+AOy4XHAGTDvnQkJQ8fD/6I1CKEaX4aUkspGFtx9/X7NHw0A3q/xBUvizhQyHfWDPFj2x0DPlhA8iMq9sncLLlVCjGG2d7K8tBEbOY4iZR0tIL04sDCcVDgUNd4SRUSPdHKYLasRiAHSiYiFZfLPvzofnkxT4p3HmGLwsqtKC4iLmD8Fr0Ibp//RgGsPeECUgx7XHYQSzuBkqQXBBN/N+kQZO3p1UN2GH6N7EWsI1xT/heShxC4lj80UmVSCJhuP7OeIN1OWkz+Tdlp0UL6NYcoNHT/PEmHCj+M9raaNgz804RgN3wOltEu7mOxPrwRqQ9HMEId41clrZwR/DDtFUDx/6AYCQ==,iv:/eA1EqyjWuhC3Nnhw9scut2EG/Vp5G9lzVRrgNKg3zo=,tag:JfcW4K1+KGGAXM2pHVbw6Q==,type:str]
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: gitea-helmrelease
  namespace: development
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  lastmodified: "2021-03-21T21:32:42Z"
  mac: ENC[AES256_GCM,data:ooLjOnQdtrdQeX9w3sJetSxQsx4qns7Gq656nVFTEauQb7LPYMkTrCJzp2iCpS6E0rMXY2anoluROUH0kojKuAoD3atHvScj+dsscy/9KGfxYhsIAlV/icWGmG2ZJeDh5E9uiMO0TfFKyOQfMNhURq8F5g2wflQpyKc4/DQif+o=,iv:+KYG0THFeRVGgv6OZU4MBvN5zOzIKLcMin+MbPhEI58=,tag:iydzxp4g091iUvTTOz6eZA==,type:str]
  pgp:
    - created_at: "2021-03-21T21:32:42Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQGMA/JorPHm1g9XAQv/WvC0Onjq9VPZ8dMydYVbRxL27VTwXp0VOibVWxxl99Pp
        78wV1zgxV4LLJnGTdmN48cB0RGua4uluRZSJi+z4TZ5jVaUps1L/hz0ufKb+BKq9
        STpvstdq2TxyBclIZM0eruhuqQzFDPkconHpOWaIcgqAhmslaZAQmJ3LNdteVuKk
        KkSMzm+Ub4joiov0G6EBaRJz9wihM/N6llVbfiK+MC0dXQLE0/X+xZjXGmtOwzYE
        td6h2V9Pb9NOMACZkmW5gMOWi5weKnSNX8EAQOWF7mC6oiR1PsERwsMoB1MxVImG
        lMlKDRbjF75T4QTD+TTPEkExTtEO+3sUFJd6MuJkf9GPbvDlVuD/ZE3f8Y8mf0AE
        f2qKMW4CVwm40GBfemFaLUSr3HKAoM61nt7cr78zhg/vi2F05qrPT2XQqk2n9CM8
        RAgkz2APW/QWcPzSY1TViWchw1Pc2VX++nigUv9tKq9c1umL5A2o0qRGO2e+h53c
        NW6gWfOMRsEOPSJrRSxi0l4BTd1dgN3hz43I8VsYdnmg+g7wJy48NrVzFb9ongoj
        5dmRcpmFtkHrSOMnlQu2nXVEEXJU/uJ4wfHXEPRjPR3xRdzqIttmDuAKhLhm3+O1
        S/XDvfT8+vi/KuZ+r9ho
        =8u/X
        -----END PGP MESSAGE-----
      fp: C8F8A49D04A1AB639F8EA21CDBA4B1DCB1FA5BDD
  encrypted_regex: ^(data|stringData)$
  version: 3.6.1
