apiVersion: v1
data:
  values.yaml: ENC[AES256_GCM,data:PfJOsatUPYRNslp3W7teYiMDS+S/QUTg5YUwWVJeX2RzcwqitQkvPqIjT610mi7chAIKU0Ys2V5/ghsKYdYJW4q/LihwAxqwN2pgp+mztoA27/wJ96/iUYEyLICtrpBzQrdQzDBB//S+J36V4Me+KjMHMzhqxrBtErmUWfbHQDSjfBskErdNJ2bFt6q/hN0KlpR4FP0woCnNHlaw2FzC/K2+X/HqdvZFG5Iy+Pbrr3mgRrCJz3IwnOOGL758hg2m2DnZ0rfWtpZqtq+0T3NWL2UiFwMBhrxyA52/w2esiwRShWpEt9kvSuCZPu/3/YiR4YgivzZptCE60JGOLOL1R86sCEHTxH1cecroLiLpkteYLYYVeIPbXIXEl2xtQ4wO6DfypTYDvFIkk25vrCErgqfUdUntmTcXYtn0bwWesGZXPcU15MVTPtfX7hnEwWEfxkt6Veefo9XTwBGkA0QM1/LB0/SB9/Z8nQkDxRRTkFdVM0a7mYern5I1balMcAni3jrlWcxtOfIH8NqIpph9F0mgeVS0ofs/LTlnF63upAOtMR8splgqrIY0z3is8Z2gx++gw/aoMalEmkiZXbj7DSjiexVOl+8=,iv:D9vJhX1IyPj8I5UZxA+UQqEiuHeKFdvAw52KoB47YFY=,tag:6ijAuQbkmycKbmvww8Hx5A==,type:str]
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: gitea-helmrelease
  namespace: development
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  lastmodified: "2020-12-08T23:44:15Z"
  mac: ENC[AES256_GCM,data:chmtuxyjD4vFQYGco/0BIKLWrbFcGgbgv3j/+Nb/c3S9siaFgbfUFbmQ4RvtO+oBKFn8aA2VKPGsOZOsRSNnN92F6yjIU3xfVhxrL6OuhiI+D1v2neIO9ypyD3Fxc7TaXARYsEyUHpswx0BIMRYhm9E5l251Ptfe236IgwCTNiU=,iv:6hviPOPRC3pQNidhBL5d+65VdIN/KiTR4koqKWFboaQ=,tag:bFMXsBZL4oSuya1IUybLHQ==,type:str]
  pgp:
    - created_at: "2020-12-08T23:44:15Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQGMA/JorPHm1g9XAQv+L7UJ7AglK7jczd0leMXVj0dxRF0tcwsFM3Leba2CpEB2
        8O1Smh0Fzb09OY17z2Rer4QVBRo88f2npB0lCHAyQs+o3187x/wejpe4L8Wdk2uU
        V7lq3Yk/2liw9oaRMFayMjQGox2U5jPEBjPeijxSWHBQ1o0toV+ehEHniE9lORdQ
        1Enw/nFHTtKzGfCcDcMwuasDhJvrizwU1iwLJNjNIMBCTeZDFmwdsmEpRobKRPqR
        CfwW5g0+mug0f/A17XaDtYEWyVbTtqKR3lehj2f6lD+opZ2x3MZN+zUCfIvi5Kzw
        mV2s5X0HmFRwDStImmcdCBl8FXfzK1zdbHtnFVukP3VXsOPwBzid0rSQoPEJrzcO
        F/bsfUkyzmYfnfsVRwNHQTifl5FhmNKLzuEBBSL+sGeT0h7Lqg8f+hUrcs/BA7SP
        FtYxmStc4jTMM0QpUWCJVx0tRHnsYF/k5DrU5E/xKxq/znxzs7ZuW0F15DoQV7Q3
        GcUvqCNnjAPOmvYCGx5B0l4BlIRHZhjvLyaOM4FjjrjsFhGeVJRmvlLYif7ysIwS
        ObH3ugdg+v0oNTtkEVd1+gt3Uckxl/4L/AcmZbLTrFrbxkbdY/KtH5ufUTOuEccP
        F69H3yoj2hBf1ntV2DzK
        =Lles
        -----END PGP MESSAGE-----
      fp: C8F8A49D04A1AB639F8EA21CDBA4B1DCB1FA5BDD
  encrypted_regex: ^(data|stringData)$
  version: 3.6.1
