---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zigbee2mqtt
      version: 7.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: koenkk/zigbee2mqtt
      tag: 1.18.2
    env:
      TZ: Europe/Paris
      ZIGBEE2MQTT_DATA: /data
    config:
      homeassistant: true
      device_options:
        retain: true
      permit_join: true
      mqtt:
        base_topic: zigbee2mqtt
        server: "mqtt://vernemq"
        user: "${SECRET_MQTT_USERNAME}"
        password: "${SECRET_MQTT_PASSWORD}"
      serial:
        port: /dev/ttyUSB0
      advanced:
        log_output:
          - console
        network_key:
          - 204
          - 61
          - 75
          - 23
          - 44
          - 230
          - 24
          - 203
          - 53
          - 5
          - 248
          - 32
          - 50
          - 84
          - 44
          - 159
      frontend:
        port: 8080
      experimental:
        new_api: true
    securityContext:
      privileged: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/auth-url: "http://authelia.networking.svc.cluster.local/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://login.${SECRET_CLUSTER_DOMAIN}/"
      hosts:
        - host: "zigbee.${SECRET_CLUSTER_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "zigbee.${SECRET_CLUSTER_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: zigbee2mqtt-config
        mountPath: "/data"
    additionalVolumeMounts:
      - name: usb
        mountPath: /dev/ttyUSB0
    additionalVolumes:
      - name: usb
        hostPath:
          path: /dev/ttyUSB0
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - {key: "feature.node.kubernetes.io/custom-zigbee", operator: In, values: ["true"]}
