---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: lidarr
      version: 9.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: ghcr.io/k8s-at-home/lidarr
      tag: v0.8.1.2169
      pullPolicy: IfNotPresent
    env:
      TZ: "Europe/Paris"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    persistence:
      config:
        enabled: true
        existingClaim: lidarr-config
    additionalVolumeMounts:
      - name: nfs-music-media
        mountPath: "/mnt/storage/music"
      - name: qbittorrent-cache
        mountPath: "/downloads"
    additionalVolumes:
      - name: nfs-music-media
        persistentVolumeClaim:
          claimName: nfs-music-media
      - name: qbittorrent-cache
        persistentVolumeClaim:
          claimName: qbittorrent-cache
    resources:
      requests:
        memory: 500Mi
        cpu: 500m
      limits:
        memory: 1500Mi
    service:
      annotations:
        prometheus.io/probe: "true"
        prometheus.io/protocol: http
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/auth-url: "http://authelia.networking.svc.cluster.local/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://login.${SECRET_CLUSTER_DOMAIN}/"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header Accept-Encoding "";
          sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://gilbn.github.io/theme.park/CSS/themes/lidarr/space-gray.css"></head>';
          sub_filter_once on;
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/appName: "Lidarr"
        forecastle.stakater.com/icon: "https://raw.githubusercontent.com/lidarr/Lidarr/14c3d31c2bf64893e9e7c137a04bfc096e6d36fe/frontend/src/Content/Images/Icons/android-chrome-192x192.png"
        forecastle.stakater.com/network-restricted: "true"
      hosts:
        - host: lidarr.${SECRET_CLUSTER_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "lidarr.${SECRET_CLUSTER_DOMAIN}"
