apiVersion: v1
data:
  values.yaml: ENC[AES256_GCM,data:3ZJOnNsa7uIOQEVh+JbOjg5S+FtdFAe0rM3QlVHY+qic19As3UU1IGM4vjMIi0VVvhq/ZssBZ2SVfEivz0nKQ1ukGyLf6q9bWK7sNM0LDjrLrrxxdOESFPga4Q18XE5RegNhJzTNkAL8IPBwed4ZCMWXKEjbhni9hDnhzqHlxibZQfmxcQZaJPAAXmiwS/dwxKwUR9saT3YLEy+b8aaJqzqYnzIaDabQnen22SyxX3szKsE/6ukc6zji+TkXPT18yEIbhNtrqgia8a1VbQRqw0J+227TXKL78FepEqXrC5R5tT/tlKWnN/o+NcbZjuZn5jNDqfQRSXEEVeek1ItQt2scNQ5ufnaIo5HQ8dhmtR8Gw4iSJU3DF3FqxssmcBLj6+riQNZObtleE0P+D3yN1si5EX+is6fDyk58fmEfTi6YKd5KQ9Jtp7PTKwmcVqXJL0Mxkml+8SyoOVYRtu5LHbWgeqAkGtrhUitXLYV9HjrzX+i6+09c6ZZ//0jnUDasrTTPsZaPo7g=,iv:4iCjAc5Y3ovIhj6WeH9i+6SDPR7B4+iBaOGuBJieBdE=,tag:6i9bmwBy5VXFoKDvHQ543g==,type:str]
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: bazarr-helmrelease
  namespace: media
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  lastmodified: "2020-11-23T17:43:23Z"
  mac: ENC[AES256_GCM,data:PmERPQPHlueaSPfLCjmU8t9s9NEFhCyUK9Cr0vY0B4u8JZb8NHO8F7vgZtAwKeIqeV51jYOTmywpb65+qdOOpwe9ZVJdihEDmW874Vk8s84v/l0emLHo0T/82Se/tRHK2QxePCvr7cj0SGSFEAkBPNaeWSqiir8UnW9fxCWa3Mw=,iv:jhpGKRppev6twl4L6H6CHbFfaY4yZhQo3cH4UkLN9Io=,tag:HEKXiq9+qj4xbZ0b2e+tgA==,type:str]
  pgp:
    - created_at: "2020-11-23T17:43:23Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQGMA/JorPHm1g9XAQwAhLOfuPZQnGmj9+54hO6N616v+BzP7cemwirHf58X2NQ/
        lDW54Ju4IL7EFE3ICBD8qPywmPznOx+7zKPvaVQFtt4Y4fQQpkYGL2tNTSvW95hs
        aTD+ZKJzVmDhn0PfvFmdC8zspRqS+mvs8sBtpNAKG9XMXafz20Acq8rEToNpHjHZ
        sDf3VtW3eI8e76OTO5OGpH2dZR6NhFMEYDTi9K830LrRANkdZk/7nwq1p3jS0vfz
        wdkchvHUr8SnsuRRJYom90XK2DBIe9CTUscTe4ff30OI9YTpGESlYy55uC3vZHNE
        fUo0iXyK+bFv0MxOVl2QcOLlwVNJiU7aWGLqlDZP+Qfv2YBAFDoUulT587XT1DMt
        pQlpDJt5dYHsZNypSB8yjAbR2H3renCtaQbY2W/pgzc3OYhZN1k4U6PxrDGK1tvy
        EZtXqZ7o+N3F8e995BA68ZZU2wUgApj8M9iD/k5CFdsGC9FObJTTDCQooAdmekw3
        Q3L16DGlP4HbW4jNKCtx0l4BWnvfGYQgT21jomayT9YXlZfoyxjgJwM2N8w8dzLv
        Re5DmsFOkGOGJbMehHjzZ4eHeEhz5Rj1OR4zQ7eU9+AmMoJ0Yy5DboQFm9Q49Qqd
        6xx8toMKs2NRND+x0is0
        =7suV
        -----END PGP MESSAGE-----
      fp: C8F8A49D04A1AB639F8EA21CDBA4B1DCB1FA5BDD
  encrypted_regex: ^(data|stringData)$
  version: 3.6.1
