apiVersion: v1
data:
  values.yaml: ENC[AES256_GCM,data:8aXhvFviB5rMMvOJ7aKkLDLvZ8BwwRHSi2jwqSoncJtGDWtcCHPdAVlLVmoH81mM0nqd6OPiIUqor1Ml5AXJONrxsrqxwiGyfJ4JJ749epJS7KuzNxhx31cbkehWrYbZNEbO4hxu5YqeIwbSK4mZMRarsZO+mHD8NxU02Su1Dugy,iv:QwSYxW3VQR6eyjbIdfeF21uUijL9KrtY7qR9wFSZ68I=,tag:QAuabBgpO6FVYdQnFjE8kw==,type:str]
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: lychee-helmrelease
  namespace: media
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  lastmodified: "2021-03-21T21:21:49Z"
  mac: ENC[AES256_GCM,data:bPLRT3FV6ugE2T/8lizOIi7Hfy8cYAOVFj981TZqpmgoVUI1dtrq/h9mvI9T8jBEwtYl2Ye0HrGzfWpr0Sb6fbiORrtqmxDLe/hUUtaFbTPiIiM/AzNEz5fq2yQBx5TcVI9uRWZ0HOl4Zcwtg2KHAULs2D2+WAlrtf8HfGYRC5E=,iv:7XxC35KjPfjV6onWrTdrMBQ3b2afZNBRWwicrDyfGSM=,tag:1nt3ZleqIVu6QDtY+DWOrw==,type:str]
  pgp:
    - created_at: "2021-03-21T21:21:48Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQGMA/JorPHm1g9XAQv/fOkhF1AJxFxtNB1mGtPfqcUefeImzA+VOCmPPrWVJKFt
        wAS9EnUdb6Q5dTPJlv4B2z1fUKMApz5bedzPA9ysNNiWfeMQSrdd7BStR0YcbQHg
        ST0bOuWlm+EIuKPIul5LPxVrM5fEJv8iyxb8KSlsAhMmVidHcIJ18BjvGg7tanKc
        Ib8RwCipBdIERJxDl5AoDGTIeGcYVY+zs8UhFAFm4kJBRvVECTupdJG/BsVz5cTc
        D1lEk+VYPnBer+yd6qi1L/MwUPUFxPQvH42ZvFqDOhDxa7ydQRanUGpOKEizPy6w
        lD1TNywUG+xvcH+Y4ky22db8a8tPEiEZRrLzamSwfYhcerAtdQ3AyJCsoIR3Z41C
        WgIVMhCIvqM6gCctGPtRhvXTKQqj1mQarmRPI0MLKefoZutnlzOBWXeEVqV5kPNY
        Vw+nRbayzWRe17BD+umjmQ+/pH+fS7gzQ9gSuT/vugYIyYfai1eIPCp8b6X32e2I
        WT+w3/SYepsdFTlC0LoK0l4BG3pcKTMyTIB6Bzcn8BU8aTXDsy0dIy/acjiKWMds
        tORqn0MRmUZCaNI6bSNt4ai8e5/8pMtlmAG9pl3BPwz6gyQwuzSyB7mR+eYS84M1
        85+j7TT/uoDOsfy3ndWr
        =T+zv
        -----END PGP MESSAGE-----
      fp: C8F8A49D04A1AB639F8EA21CDBA4B1DCB1FA5BDD
  encrypted_regex: ^(data|stringData)$
  version: 3.6.1
