apiVersion: v1
data:
  values.yaml: ENC[AES256_GCM,data:Q6OhVatRWDBpt6xoDNKm+jyGC5AzxRwmRpZXmWoQEYBEJurFteRpZI7TK2qaMTn8VKSE89mIRtJgQUGU/NSk4weLoIdDco8nGwoDbmBmklIgz7279hy4/34ZH4ZdNOECVm93wFinIFulvwGK11N8cXxDaLkp1cMw2YjaeLErnXZF7BteFysdiQ5JQ4CWt8KH8IZvX+qjX1eLxQ==,iv:6IGZEemZ6qVQE+VtE/p45uSq5L3NAvxUyJOoJrQ/ZkQ=,tag:i53ijoxSnBqvpNT3dVipVw==,type:str]
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: navidrome-helmrelease
  namespace: media
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  lastmodified: "2020-12-12T01:00:12Z"
  mac: ENC[AES256_GCM,data:UXhXXHAWWE3b+h//qQSxaWtnVgptIxwvNm48IrPT/RwPvUl0+h4EXO3J/g2I3G0jFDOFj+okeU1lYOStWdqDP8KT/5dhiadRW1E1MIKCwaxr5ha4MG4A9Vij0Ph22fMBBE/EtvcwtqzLuiROxM0MElH9vc9A4s/WPydXTAE5/mU=,iv:g7SW6tvMw9UlCMyFLSoVNT/4Kw0RUAp825cWoBKLmCs=,tag:k0BrGNll0Hd30YP89czuWg==,type:str]
  pgp:
    - created_at: "2020-12-12T01:00:12Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQGMA/JorPHm1g9XAQv+LCDaz/1iAhYqxt7nRcgzcz+Lt+jJaInQxCQLrT0+rAYN
        /ILDfHMD/TNuaPsl3PNQTpkPjne6wnsHMeYQgqUtabdzlBr3+2wTWwJWKZcz8C8C
        Znwrj1sgZ2w3BZlCbJEMHCZAtCqAid7gnITbYx1cE1vSNvC9jlWkbYHtKdBLpdc+
        bpO5lajdZp/kaaBL64cqQjnVpuJN09JyB8WU2EjgXRvKKJhfXvY+Hpac9Bh38HPp
        vLLkazcQmpwgwcQ8QgLH0R+ACdoKmMViiacErkSkYznxJ6weOC+5zfRi4LbgSmjL
        mMLWuVWekLq1VbI2LpgwEKQq2ViroHmA709r/kGp6/PDLFDLNw6ALATCddg8TIDA
        E7daUjBSLbXifotAH2Xf07Vicbpr0c/395W4dYkiJ6d0hTvPccu7AH9d9pWfwmqk
        jgRGNk6GbNmVyTk0QRooW98ImzwMLQpZFRHXK/koGemO3qxwySV5ffqPocp/Q+Sn
        i0pwJkxRry5riSQMlcf60l4BE9Efllh/rTtATk3bUbxm/LeJx8cDA5mIrvhmNmcZ
        B0SbHAVcLVRhDGOSD236ZlhUSuErOHENkMcvV36qmQNbnDJQKURWiRJloQYdlweo
        U1HMpHIsoC5QpyXYB3oq
        =DFHT
        -----END PGP MESSAGE-----
      fp: C8F8A49D04A1AB639F8EA21CDBA4B1DCB1FA5BDD
  encrypted_regex: ^(data|stringData)$
  version: 3.6.1
