---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 7.2.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: homeassistant/home-assistant
      tag: 2021.4.0
    env:
      TZ: "Europe/Paris"
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      annotations:
        prometheus.io/probe: "true"
        prometheus.io/protocol: http
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
        - host: hass.k3s.xpander.ovh
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "hass.k3s.xpander.ovh"
    prometheus:
      serviceMonitor:
        enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: hass-config
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 3.9.2
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
          hosts:
            - host: hass-config.k3s.xpander.ovh
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - hass-config.k3s.xpander.ovh
        volumeMounts:
          - name: config
            mountPath: /config
    resources:
      requests:
        cpu: 500m
        memory: 1000Mi
      limits:
        memory: 2500Mi
    postgresql:
      enabled: false
  valuesFrom:
    - kind: ConfigMap
      name: hass-helmrelease
