---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home
spec:
  releaseName: node-red
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: node-red
      version: 7.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nodered/node-red
      tag: 1.2.9-12-minimal
    env:
      TZ: "Europe/Paris"
      NODE_RED_ENABLE_PROJECTS: "true"
      NODE_RED_ENABLE_SAFE_MODE: "false"
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    persistence:
      data:
        enabled: true
        mountPath: /data
        existingClaim: node-red-config
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/auth-url: "http://authelia.auth.svc.cluster.local/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://login.k3s.xpander.ovh/"
      hosts:
      - host: node-red.k3s.xpander.ovh
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - node-red.k3s.xpander.ovh
