---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelstories
  namespace: home
  labels:
    app.kubernetes.io/instance: travelstories
    app.kubernetes.io/name: travelstories
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: travelstories
      app.kubernetes.io/name: travelstories
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: travelstories
        app.kubernetes.io/name: travelstories
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: travelstories
          image: docker-registry.development.svc.cluster.local/homelab/travelstories:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: caddyfile
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
      volumes:
        - name: caddyfile
          configMap:
            name: travelstories-caddyfile
      dnsConfig:
        options:
          - name: ndots
            value: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: travelstories-caddyfile
  namespace: home
data:
  Caddyfile: |+
    :80

    file_server
    root * /srv
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/probe: "true"
    prometheus.io/protocol: http
  labels:
    app.kubernetes.io/instance: travelstories
    app.kubernetes.io/name: travelstories
  name: travelstories
  namespace: home
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: travelstories
    app.kubernetes.io/name: travelstories
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  labels:
    app.kubernetes.io/instance: travelstories
    app.kubernetes.io/name: travelstories
  name: travelstories
  namespace: home
spec:
  rules:
    - host: travelstories.k3s.xpander.ovh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: travelstories
                port:
                  number: 80
  tls:
    - hosts:
        - travelstories.k3s.xpander.ovh
