---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-gitea
  namespace: development
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 5Gi