---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone-runner-kube
  namespace: development
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.drone.io
      chart: drone-runner-kube
      version: 0.1.5
      sourceRef:
        kind: HelmRepository
        name: drone-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: drone/drone-runner-kube
      tag: 1.0.0-beta.5
    env:
      DRONE_RPC_PROTO: http
      DRONE_NAMESPACE_DEFAULT: development
      DRONE_RPC_HOST: drone.development.svc.cluster.local
      DRONE_SECRET_PLUGIN_ENDPOINT: http://drone-kubernetes-secrets:3000
    rbac:
      buildNamespaces:
        - development
  valuesFrom:
    - kind: ConfigMap
      name: drone-runner-kube-helmrelease
      optional: false
