---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone
  namespace: development
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.drone.io
      chart: drone
      version: 0.1.7
      sourceRef:
        kind: HelmRepository
        name: drone-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: drone/drone
      tag: 1.9.2
    env:
      DRONE_SERVER_PROTO: https
      DRONE_GIT_ALWAYS_AUTH: true
      DRONE_LOGS_TEXT: true
      DRONE_LOGS_PRETTY: true
      DRONE_LOGS_COLOR: true
    persistentVolume:
      enabled: true
      existingClaim: drone-config
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/enable-global-auth: "false"
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "80"
  valuesFrom:
  - kind: ConfigMap
    name: "helmrelease-development-drone"
    optional: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-config
  namespace: development
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 10Gi