---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone
  namespace: development
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.drone.io
      chart: drone
      version: 0.1.7
      sourceRef:
        kind: HelmRepository
        name: drone-charts
        namespace: flux-system
      interval: 5m
  values:
    updateStrategy:
      type: Recreate
    image:
      repository: drone/drone
      tag: 1.10.1
    persistentVolume:
      enabled: true
      existingClaim: drone-config
    env:
      DRONE_SERVER_PROTO: https
      DRONE_GIT_ALWAYS_AUTH: true
      DRONE_LOGS_TEXT: true
      DRONE_LOGS_PRETTY: true
      DRONE_LOGS_COLOR: true
      DRONE_SERVER_HOST: drone.k3s.xpander.ovh
      DRONE_GITEA_SERVER: https://gitea.k3s.xpander.ovh
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        prometheus.io/probe: "true"
      hosts:
        - host: drone.k3s.xpander.ovh
          paths: ["/"]
      tls:
        - hosts:
            - drone.k3s.xpander.ovh
  valuesFrom:
    - kind: ConfigMap
      name: drone-helmrelease
      optional: false
