---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone-kubernetes-secrets
  namespace: development
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.drone.io
      chart: drone-kubernetes-secrets
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: drone-charts
        namespace: flux-system
      interval: 5m
  values:
    rbac:
      enabled: false
    env:
      KUBERNETES_NAMESPACE: development
  valuesFrom:
    - kind: ConfigMap
      name: drone-kubernetes-secrets-helmrelease
      optional: false
