---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone
  namespace: development
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.drone.io
      chart: drone
      version: 0.1.7
      sourceRef:
        kind: HelmRepository
        name: drone-charts
        namespace: flux-system
      interval: 5m
  values:
    updateStrategy:
      type: Recreate
    image:
      repository: drone/drone
      tag: 1.10.0
    persistentVolume:
      enabled: true
      existingClaim: drone-config
  valuesFrom:
  - kind: ConfigMap
    name: "helmrelease-development-drone"
    optional: false
