---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: development
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://dl.gitea.io/charts
      chart: gitea
      version: 2.1.1
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      enabled: true
      size: 10Gi
      existingClaim: "gitea-config"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/proxy-body-size: 128m
        prometheus.io/probe: "true"
    service:
      http:
        port: 3000
      ssh:
        annotations:
          prometheus.io/probe: "true"
          prometheus.io/protocol: tcp
        type: LoadBalancer
        port: 22
        externalTrafficPolicy: Local
        externalIPs:
          - 192.168.9.209
    gitea:
      config:
        APP_NAME: "Homelab Gitea"
        database:
          DB_TYPE: postgres
        server:
          SSH_PORT: 22
          SSH_LISTEN_PORT: 22
        respository:
          DEFAULT_PRIVATE: true
        admin:
          DISABLE_REGULAR_ORG_CREATION: true
        security:
          PASSWORD_COMPLEXITY: "lower,upper"
          MIN_PASSWORD_LENGTH: 12
        service:
          DISABLE_REGISTRATION: true
          REQUIRE_SIGNIN_VIEW: true
      database:
        builtIn:
          postgresql:
            enabled: false
        postgresql:
      cache:
        builtIn:
          enabled: true
    memcached:
      image:
        repository: bitnami/memcached
        tag: 1.6.9
      service:
        port: 11211
  valuesFrom:
    - kind: ConfigMap
      name: helmrelease-development-gitea
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-config
  namespace: development
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 15Gi
