---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: development
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.runix.net
      chart: pgadmin4
      version: 1.6.0
      sourceRef:
        kind: HelmRepository
        name: runix-charts
        namespace: flux-system
      interval: 5m
  values:
    strategy:
      type: Recreate
    image:
      repository: dpage/pgadmin4
      tag: 5.0
      pullPolicy: IfNotPresent
    service:
      annotations:
        prometheus.io/probe: "true"
        prometheus.io/protocol: http
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        prometheus.io/probe: "true"
      hosts:
        - host: pgadmin.k3s.xpander.ovh
          paths:
            - /
      tls:
        - hosts:
            - pgadmin.k3s.xpander.ovh
    persistentVolume:
      enabled: true
      existingClaim: pgadmin-config
  valuesFrom:
    - kind: ConfigMap
      name: pgadmin-helmrelease
