---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pyload
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: pyload
      version: 4.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: linuxserver/pyload
      tag: version-5f5aaf56
      pullPolicy: IfNotPresent
    env:
      TZ: "Europe/Paris"
    persistence:
      config:
        enabled: true
        existingClaim: pyload-config
    additionalVolumeMounts:
      - name: nfs-downloads-media
        mountPath: "/mnt/storage/downloads"
    additionalVolumes:
      - name: nfs-downloads-media
        persistentVolumeClaim:
          claimName: nfs-downloads-media
    resources:
      requests:
        memory: 1Gi
        cpu: 100m
      limits:
        memory: 5Gi
    service:
      annotations:
        prometheus.io/probe: "true"
        prometheus.io/protocol: http
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/auth-url: "http://authelia.networking.svc.cluster.local/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://login.${SECRET_CLUSTER_DOMAIN}/"
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/appName: "pyLoad"
        forecastle.stakater.com/icon: "https://raw.githubusercontent.com/pyload/pyload/main/media/logo.png"
        forecastle.stakater.com/network-restricted: "true"
      hosts:
        - host: pyload.${SECRET_CLUSTER_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "pyload.${SECRET_CLUSTER_DOMAIN}"
