---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 3.28.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 5m
  values:
    controller:
      replicaCount: 2
      service:
        type: LoadBalancer
        externalIPs:
          - 192.168.169.101
        externalTrafficPolicy: Local
      publishService:
        enabled: true
      config:
        ssl-protocols: "TLSv1.3 TLSv1.2"
        custom-http-errors: 404,401,403,500,503
        enable-vts-status: "false"
        hsts-max-age: "31449600"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: kube-system
          namespaceSelector:
            any: true
      extraArgs:
        default-ssl-certificate: "kube-system/letsencrypt-default-cert"
      resources:
        requests:
          memory: 250Mi
          cpu: 25m
        limits:
          memory: 750Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - ingress-nginx-external
              topologyKey: "kubernetes.io/hostname"
    defaultBackend:
      enabled: true
      image:
        repository: billimek/custom-error-pages
        tag: 0.4.4
      resources:
        requests:
          memory: 250Mi
          cpu: 25m
        limits:
          memory: 350Mi
    #tcp:
    #  8086: monitoring/influxdb:8086
