---
apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-trash-updater-config
  namespace: media
data:
  trash.yaml: |
    # A starter config to use with Trash Updater. Most values are set to "reasonable defaults".
    # Update the values below as needed for your instance. You will be required to update the
    # API Key and URL for each instance you want to use.
    #
    # Many optional settings have been omitted to keep this template simple.
    #
    # For more details on the configuration, see the Configuration Reference on the wiki here:
    # https://github.com/rcdailey/trash-updater/wiki/Configuration-Reference

    # Configuration specific to Radarr.
    radarr:
      # Set the URL/API Key to your actual instance
      - base_url: http://radarr:7878
        api_key: ${SECRET_RADARR_API_KEY}

        # Which quality definition in the guide to sync to Radarr. Only choice right now is 'movie'
        quality_definition:
          type: movie
