---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 10.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.6.1196
      pullPolicy: IfNotPresent
    env:
      TZ: "Europe/Paris"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/auth-url: "http://authelia.networking.svc.cluster.local/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://login.${SECRET_CLUSTER_DOMAIN}/"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header Accept-Encoding "";
          sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://gilbn.github.io/theme.park/CSS/themes/sonarr/space-gray.css"></head>';
          sub_filter_once on;
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/appName: "Sonarr"
        forecastle.stakater.com/icon: "https://raw.githubusercontent.com/Sonarr/Sonarr/develop/Logo/256.png"
        forecastle.stakater.com/network-restricted: "true"
        # -- Nginx client Body Buffer Size
        nginx.ingress.kubernetes.io/client-body-buffer-size: "20m"
        # -- Nginx Proxy Body Size
        nginx.ingress.kubernetes.io/proxy-body-size: "20m"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
      hosts:
        - host: sonarr.${SECRET_CLUSTER_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "sonarr.${SECRET_CLUSTER_DOMAIN}"
    additionalVolumeMounts:
      - name: nfs-video-media
        mountPath: "/mnt/storage/video"
      - name: qbittorrent-cache
        mountPath: "/downloads"
    additionalVolumes:
      - name: nfs-video-media
        persistentVolumeClaim:
          claimName: nfs-video-media
      - name: qbittorrent-cache
        persistentVolumeClaim:
          claimName: qbittorrent-cache
    resources:
      requests:
        memory: 500Mi
        cpu: 500m
      limits:
        memory: 1500Mi
    service:
      annotations:
        prometheus.io/probe: "true"
        prometheus.io/protocol: http
