---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarr-trash-updater-config
  namespace: media
data:
  trash.yaml: |
    # A starter config to use with Trash Updater. Most values are set to "reasonable defaults".
    # Update the values below as needed for your instance. You will be required to update the
    # API Key and URL for each instance you want to use.
    #
    # Many optional settings have been omitted to keep this template simple.
    #
    # For more details on the configuration, see the Configuration Reference on the wiki here:
    # https://github.com/rcdailey/trash-updater/wiki/Configuration-Reference

    # Configuration specific to Sonarr
    sonarr:
      # Set the URL/API Key to your actual instance
      - base_url: http://sonarr:8989
        api_key: ${SECRET_SONARR_API_KEY}

        # Quality definitions from the guide to sync to Sonarr. Choice: anime, series, hybrid
        quality_definition: series

        # Release profiles from the guide to sync to Sonarr. Types: anime, series
        # You can optionally add tags and make negative scores strictly ignored
        release_profiles:
          - type: series
            filter:
              include_optional: true
            tags:
              - tv
