---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flood
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: flood
      version: 4.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: jesec/flood
      tag: 4.5.4
      pullPolicy: Always
    env:
      FLOOD_OPTION_RUNDIR: /data
      FLOOD_OPTION_AUTH: "none"
      FLOOD_OPTION_QBURL: "http://qbittorrent:8080"
      FLOOD_OPTION_QBUSER: admin
      FLOOD_OPTION_QBPASS: ${SECRET_QBITTORRENT_PASSWORD}
    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/auth-url: "http://authelia.networking.svc.cluster.local/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://login.${SECRET_CLUSTER_DOMAIN}/"
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/appName: "Flood"
        forecastle.stakater.com/icon: "https://raw.githubusercontent.com/jesec/flood/master/flood.svg"
        forecastle.stakater.com/network-restricted: "true"
      hosts:
        - host: flood.${SECRET_CLUSTER_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "flood.${SECRET_CLUSTER_DOMAIN}"
    persistence:
      data:
        enabled: true
        existingClaim: flood-config
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
    service:
      annotations:
        prometheus.io/probe: "true"
        prometheus.io/protocol: http
