---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config
  namespace: network
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 10Gi
