---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    strategy:
      type: Recreate
    image:
      repository: jacobalberty/unifi
      tag: 6.1.71
      pullPolicy: IfNotPresent
    persistence:
      enabled: true
      existingClaim: unifi-config
    timezone: "Europe/Paris"
    runAsRoot: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/proxy-body-size: 10m
      hosts:
        - unifi.k3s.xpander.ovh
      tls:
        - hosts:
            - unifi.k3s.xpander.ovh
    guiService:
      type: LoadBalancer
      externalIPs:
        - 192.168.169.103
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
        prometheus.io/probe: "true"
        prometheus.io/protocol: tcp
    controllerService:
      type: LoadBalancer
      externalIPs:
        - 192.168.169.103
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
        prometheus.io/probe: "true"
        prometheus.io/protocol: tcp
    stunService:
      type: LoadBalancer
      externalIPs:
        - 192.168.169.103
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    discoveryService:
      type: LoadBalancer
      externalIPs:
        - 192.168.169.103
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    resources:
      requests:
        memory: 2Gi
        cpu: 100m
