apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app.kubernetes.io/instance: travelstories
    app.kubernetes.io/name: travelstories
  name: travelstories
  namespace: home
spec:
  rules:
    - host: ENC[AES256_GCM,data:wysuuM0T4vwfX4SBMqQwmKN8ERqDNzkfR9BY+q0=,iv:j4EthFTogfxVpLOBFw1kzYwNWS/XSZWqrYGP7xgRz6A=,tag:2fE3HbPmPMrGtVy4ePa28Q==,type:str]
      http:
        paths:
          - path: ENC[AES256_GCM,data:gQ==,iv:TnqEQ4YC8olqCEKKnqbaCIzOV+iNdJxbhB7Rc3iAbvs=,tag:JkBVvnUNJKakTigMzt3TmA==,type:str]
            pathType: ENC[AES256_GCM,data:q0c7nZou,iv:aOnJfo+Zwl0pirfGbLxdVcJ8yMa+93h2GeDnxrOVo5A=,tag:li3w35JDmn9+GfFW3KaKmw==,type:str]
            backend:
              service:
                name: ENC[AES256_GCM,data:7AD4i3dkUe7GWow6hA==,iv:/vpCTe1q/VjrtzB+ADDyGLehyZgfZQl+VXU5VOSs2H4=,tag:7L0aW13AhwWIjxKhV/pPQA==,type:str]
                port:
                  number: ENC[AES256_GCM,data:7gI=,iv:RXA7zcw7v7mkh0muDjVAp/uj+i6HGNkBbx89Q2SOVlo=,tag:3h6EIxMFv2DnyJ54ilZO3w==,type:int]
  tls:
    - hosts:
        - ENC[AES256_GCM,data:bkIhd3D01yc72BxBBMuB8jlWynQ2v4LdIzpHvwg=,iv:wTDz35pJ1Apc+bQ3R15eeZKLfN+fkbLvdNu7Tv7FdYU=,tag:jSWQD1bCb3n6Saiglon90A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  lastmodified: "2021-03-21T16:58:24Z"
  mac: ENC[AES256_GCM,data:ds6XaErKpW2pq+u0IOOQoxTXA1OJmfjSJcmTVHyzlV8LHxxuZNucAG2HgKzlKvkAXbtdIxqJqQ2aIXtS8zIa3ZorZeyQMbRT35H2ICIx3Q+mZElN0ZHwA71oKA0AQCDKy94eBFvm9aSj6J6hAEk2v153RLOH/P5KbGoJJR6TyiQ=,iv:hMD7eZzHr0xzRr8mwDyWAaWl0Bgzr84chyrnmjkbXEE=,tag:q1xfgcALN7RAsvEFadeEWw==,type:str]
  pgp:
    - created_at: "2021-03-21T16:58:24Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQGMA/JorPHm1g9XAQv+O0Ydubj+j/9or/suuA2y86yab0K9ECl+aoW5YldxbiGY
        PJdfBizi5iMu/Uqk99SOOqzkpP2BOsvBDD081aXQFbxxNeuqgsdEqRIvN6Wvpw2I
        4NxFJAP/80/OE5P0BnSWNcZhRCyyecw8SqOAdze+oyOItVhzbIdMPo8nGEyM3Ebl
        PInHwpsQ6dRKSU9luHrgpwdzkzwkvjdso6BJPbUeBQJWhs9DpU98VWIXZhNESaBQ
        nenpyRqm7tfh3GL9KqKBdGwijsuN3YzJx62n+cMzT8fdMOdELGx03ksEjzBzJvX1
        Bz3aue3Ou+bI+6HUR1BmKqyi1VOBaviIkJGa/AZHr8R9uDXUeBmXmhdelahWhvPg
        41dNSKSYqjakbyohrdDZ+S75rDPdxvbxrS6HqoQ9zuWVQ+weMPZBzCBTN6COU1NR
        Fp0szN1CtfOeImMl40sg6bh2U++fpR6n7AZjG5n3jL5i1veqvxaOMXv5MLmc+SYR
        x9DDJSkPy+z/8PkjTmlR0l4BME1dKQd50YHg4YdfLCJRryUhymag/6q6oSCLM4YU
        /Mev4olyujeVI7o4f60L4Rw3Sqtz5FUXuVb7veKnNTFBKPzvhK3eTwHSpnlotlqn
        yCWuYvdp68FDuov4gAmD
        =rets
        -----END PGP MESSAGE-----
      fp: C8F8A49D04A1AB639F8EA21CDBA4B1DCB1FA5BDD
  encrypted_regex: ^(spec|stringData)$
  version: 3.6.1
