apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelstories
  namespace: home
  labels:
    app.kubernetes.io/instance: travelstories
    app.kubernetes.io/name: travelstories
spec:
  replicas: ENC[AES256_GCM,data:BQ==,iv:yB2mG8RlP3mIpqW2Nr2LA/ODapgwxDuo3SaoH6EdWtk=,tag:LrM/VRgJEMWBW5JZGfN8uQ==,type:int]
  selector:
    matchLabels:
      app.kubernetes.io/instance: ENC[AES256_GCM,data:/GxErUb9mYp/zMSiIg==,iv:o9TN/Ls8Q+Bh75LWD84YNBGXrJZgTm+/2aK17hKMDYs=,tag:m7TfFrSCmqrUlxDciCzlKg==,type:str]
      app.kubernetes.io/name: ENC[AES256_GCM,data:b6wqWgAu9bPiCJsSVQ==,iv:VywDPRKiFEGShFDkH/MkrIw3Sa7I3tzyxNgO6pdMjbs=,tag:Jgp9C6x71UUFVcmm0UN/Ww==,type:str]
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ENC[AES256_GCM,data:6gHFjM9CjDfxVwxeWA==,iv:G01AZBPMbqtcXVCIY3zLkHUHcrEhHZeTaRxbhpYVmLI=,tag:XXSLXW+MxU8nzytLOZ1K6A==,type:str]
        app.kubernetes.io/name: ENC[AES256_GCM,data:mIkP9IoTVKYtLMe1fg==,iv:yM4ZbRTzs6G1Y3eHOGqx36eDYn4iegRlMWmOfoBHp7o=,tag:Iz1NmqFTRU1XH8BhTVvcYw==,type:str]
    spec:
      imagePullSecrets:
        - name: ENC[AES256_GCM,data:0hKHFvDvkw==,iv:PeL1HeBn39rPQvOSiF/FHDKYvfij3EWSAddGrh5kT3s=,tag:3iRlWjllUkVpMWpZn8FbLQ==,type:str]
      containers:
        - name: ENC[AES256_GCM,data:H8TQzAJFa0Q70qx4hw==,iv:QLbG79x0dOU6qsbaexJPVhA6hHSbudFAqNaUvoqZLqg=,tag:p+8VnLYpt7r1JEwdDAdowQ==,type:str]
          image: ENC[AES256_GCM,data:WaSZpyUURoaJqBCP6pipnQy/kQcIJM+MkC5RjBiRLLW2PxmRy2qVaXZ8mFczixhf+xU9aA==,iv:PBzLk/evbi6HfSZFAW9CWsSkiYUMpiEpkYUqx4Vz+rc=,tag:O8qpP3t4ugihOBpzOllBIw==,type:str]
          imagePullPolicy: ENC[AES256_GCM,data:u324Y+pv,iv:Nqdz+1YYBIexF6a+ebEJC8ViQAIuTdB/hEoa7neivE8=,tag:mWNLadPrquZgWI2aAkOcag==,type:str]
          ports:
            - containerPort: ENC[AES256_GCM,data:YUc=,iv:QdBLSWLz+dejV8FjAbNOUS3SdQiMU5CgZgUSIUP5dRQ=,tag:oSZoKJW54rCOTHsjQY7oBw==,type:int]
              name: ENC[AES256_GCM,data:43TPtg==,iv:iatvbLiTVPehdqpyJIn0ZE6WdBV32R3wqcOwkx56HSs=,tag:vNqZEJBLmVQyPK9GbuhEeA==,type:str]
          volumeMounts:
            - name: ENC[AES256_GCM,data:CgRbjvR/LO59,iv:vJp9IemN9csV/jUjB9K45x3MwiMM7rU7FaSgS2so4K4=,tag:kd9m2kDGc2u6urrEz4XDrg==,type:str]
              mountPath: ENC[AES256_GCM,data:w85Zag/M87ozuNdaifp7/PaCh0s=,iv:3IlQBzR0l6Vm9ud+Y32V99aZq+wxLI49S5qv+9VLKRI=,tag:FDC8kMcQKwNgLJ/+0K5CCQ==,type:str]
              subPath: ENC[AES256_GCM,data:CPge/W+8Kz0r,iv:ejLlZyQdXnSw6rkrJJkzksHmrt2aMc2rRPIqu768+Go=,tag:at7dGgnXRe7WXFDawr8Hiw==,type:str]
      volumes:
        - name: ENC[AES256_GCM,data:/am7lUgMwhq4,iv:MpZdVJ2Na609Q+gRnk3Kobmj9oz6qYU+hNN2z3fCxiA=,tag:KYadb57rsmvbwDEPC7BpIg==,type:str]
          configMap:
            name: ENC[AES256_GCM,data:pBdZk0wzi0gBzHPSyhTSsHWBscNtM5I=,iv:O2fexbfL3Td7kjO57Iz5yIaJMlnYTYYQ2kWbae2RT2s=,tag:mz7ur9gB2Z+Gs1FbFBhhiw==,type:str]
      dnsConfig:
        options:
          - name: ENC[AES256_GCM,data:y0OCesw=,iv:Ni7elsrZxujAWqJZqBnMwWGWhFY2RA8jLEsp29zzTwI=,tag:AivWAcW7pNWUA/L9+Wq/Og==,type:str]
            value: ENC[AES256_GCM,data:Mw==,iv:EvIy3wzwMLUXsNk5R7F6lkRz5bDyU6fOwCdJzYTrUG0=,tag:3TLtlLbtJ1JudItiQH+3XA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  lastmodified: "2021-03-17T11:11:45Z"
  mac: ENC[AES256_GCM,data:WwgIJnlzYHtCnpa969V43tztPpIBNxkEcyQc9b/juDmLqjX8Z6afGs492ccyqGL7YyRBnNdt0LUfmAf3AYxnMJdDdV51lrObSAhGVDyRjBbY3Ke11JkCsLOl9rZCDVImiRfvUx2ecOsSQ5HDXE3yOBtLVxaOB3RULqJYvxFC+1o=,iv:ofE23xNsGedR+UdzOQbTUyp7hkth0eWPTHGejN5QY+w=,tag:idsb6JuS+JiIGqfucA7IXA==,type:str]
  pgp:
    - created_at: "2021-03-17T11:11:45Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQGMA/JorPHm1g9XAQv/X+hgRhDD+b7iABU9bjYPcFHKKovqYZeW1KjPqBhROGVk
        2B1BPHn88vIAoZpI+18/JFvQr8hBthHjJIOOwOb3vtcfreEFPMSg/svpau3uGwkh
        0NKFCc/La0J07QkF13OHIlzRXXW3AI90aXaIeEsmjYWms0yFejXpVC/bAp6BsRQx
        mAQOY2pXEdRV3zja7AreZP9kPHn23pZxVZ3xDASIAjfqjq5ownMhIm5l5kYK0fZc
        3Ctm/70wFoZVX9Eq5y5U7OKsBmxJSZN9n1HV9CLC4zKt7T8nIET5MuZ+ZPIR9v2w
        KiM1qMulrpFQxWaKkLXWnxtqN1cLarw2rOqxuCwGdxPp0SQSG04XBvLKox8qaRuM
        EAs7F4GKPDE5zsbIBhY0MLl7rVCUHVZ+W/j7zWw5b7Db7lkyXQMwrSnm0fp3Vyy9
        aQ5LtELBz5oHmES7NZ3X2mvTNMBFfLppSBnKkAh1dkgAYRPw2QvsTIEzexebZ7tY
        IAXgiwwOby57tDWcQSzp0l4B6+uoqhIspt1PJgL2L4J2F7+7JAO9x1MXLPoZhVPg
        asYoPAPSSq4Va/zVK3e+zQKpTHbb2ppKNUIbOQcec6GyCOWcXt26QI82kg6ldrk7
        Js7YwUTgO7yymzpvy/0I
        =8/bz
        -----END PGP MESSAGE-----
      fp: C8F8A49D04A1AB639F8EA21CDBA4B1DCB1FA5BDD
  encrypted_regex: ^(spec|stringData)$
  version: 3.6.1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app.kubernetes.io/instance: travelstories
    app.kubernetes.io/name: travelstories
  name: travelstories
  namespace: home
spec:
  rules:
    - host: ENC[AES256_GCM,data:joodqOXigNCjPH7Km0PnU+kgFijUgLzWgMZueu0=,iv:+iwdhDDkKHCLZwFVaHtTTDmdCterHpvWYDyFxfyJXyE=,tag:RQF9h19g7bj41oBD7j3aqQ==,type:str]
      http:
        paths:
          - path: ENC[AES256_GCM,data:Mg==,iv:xFCcofVe044hr5JtgYe8o/0UVGrWpkNb35TlYTstgC0=,tag:CvyGI7gj4BMRRhiXlGnLZQ==,type:str]
            pathType: ENC[AES256_GCM,data:Gj0M2271,iv:gV5GulFYLzJ7BvdzMcMl4WXnTDltpZmK5Sw7IfNPgJk=,tag:hGlGvqdXKMgqHSdL7CnA9w==,type:str]
            backend:
              service:
                name: ENC[AES256_GCM,data:HuhI2oJHQVQ8KlFA0Q==,iv:S8gbgJkujTy77Y5aipIkdq1M+mKDQSuGxj6UTUG6Yvc=,tag:tq1Y8IOq3SUwsmUoDpLUnw==,type:str]
                port:
                  number: ENC[AES256_GCM,data:SF0=,iv:uyN1MF1F0UwTTWUeKCd/+RySDb7t0uwISbLusj9g5FQ=,tag:xadXAAtUMJbrEqqzWQoTBA==,type:int]
  tls:
    - hosts:
        - ENC[AES256_GCM,data:qeEvxutAsabMrUzWAfINVaUL5QW/Z6Q1O26RVUI=,iv:UIIBXUZFM4XtWw2LgfP2Jy45BJniS6q9aYeIV3MBdm0=,tag:FOBUAOpEgJScUe6QIA/3tA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  lastmodified: "2021-03-17T11:11:45Z"
  mac: ENC[AES256_GCM,data:WwgIJnlzYHtCnpa969V43tztPpIBNxkEcyQc9b/juDmLqjX8Z6afGs492ccyqGL7YyRBnNdt0LUfmAf3AYxnMJdDdV51lrObSAhGVDyRjBbY3Ke11JkCsLOl9rZCDVImiRfvUx2ecOsSQ5HDXE3yOBtLVxaOB3RULqJYvxFC+1o=,iv:ofE23xNsGedR+UdzOQbTUyp7hkth0eWPTHGejN5QY+w=,tag:idsb6JuS+JiIGqfucA7IXA==,type:str]
  pgp:
    - created_at: "2021-03-17T11:11:45Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQGMA/JorPHm1g9XAQv/X+hgRhDD+b7iABU9bjYPcFHKKovqYZeW1KjPqBhROGVk
        2B1BPHn88vIAoZpI+18/JFvQr8hBthHjJIOOwOb3vtcfreEFPMSg/svpau3uGwkh
        0NKFCc/La0J07QkF13OHIlzRXXW3AI90aXaIeEsmjYWms0yFejXpVC/bAp6BsRQx
        mAQOY2pXEdRV3zja7AreZP9kPHn23pZxVZ3xDASIAjfqjq5ownMhIm5l5kYK0fZc
        3Ctm/70wFoZVX9Eq5y5U7OKsBmxJSZN9n1HV9CLC4zKt7T8nIET5MuZ+ZPIR9v2w
        KiM1qMulrpFQxWaKkLXWnxtqN1cLarw2rOqxuCwGdxPp0SQSG04XBvLKox8qaRuM
        EAs7F4GKPDE5zsbIBhY0MLl7rVCUHVZ+W/j7zWw5b7Db7lkyXQMwrSnm0fp3Vyy9
        aQ5LtELBz5oHmES7NZ3X2mvTNMBFfLppSBnKkAh1dkgAYRPw2QvsTIEzexebZ7tY
        IAXgiwwOby57tDWcQSzp0l4B6+uoqhIspt1PJgL2L4J2F7+7JAO9x1MXLPoZhVPg
        asYoPAPSSq4Va/zVK3e+zQKpTHbb2ppKNUIbOQcec6GyCOWcXt26QI82kg6ldrk7
        Js7YwUTgO7yymzpvy/0I
        =8/bz
        -----END PGP MESSAGE-----
      fp: C8F8A49D04A1AB639F8EA21CDBA4B1DCB1FA5BDD
  encrypted_regex: ^(spec|stringData)$
  version: 3.6.1
