---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sabnzbd
      version: 8.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sabnzbd
      tag: v3.3.1
    env:
      TZ: "Europe/Paris"
    # disable service monitoring because of ip blacklist
    # service:
    # main:
    #   annotations:
    #     prometheus.io/probe: "true"
    #     prometheus.io/protocol: http
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/auth-url: "http://authelia.networking.svc.cluster.local/api/verify"
          nginx.ingress.kubernetes.io/auth-signin: "https://login.${SECRET_CLUSTER_DOMAIN}/"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://gilbn.github.io/theme.park/CSS/themes/sabnzbd/space-gray.css"></head>';
            sub_filter_once on;
          forecastle.stakater.com/expose: "true"
          forecastle.stakater.com/appName: "SABnzbd"
          forecastle.stakater.com/icon: "https://avatars.githubusercontent.com/u/16778130?v=4"
          forecastle.stakater.com/network-restricted: "true"
        hosts:
          - host: "sabnzbd.${SECRET_CLUSTER_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "sabnzbd.${SECRET_CLUSTER_DOMAIN}"
      api:
        enabled: true
        nameSuffix: "api"
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: "sabnzbd.${SECRET_CLUSTER_DOMAIN}"
            paths:
              - path: /api
                pathType: Prefix
        tls:
          - hosts:
              - "sabnzbd.${SECRET_CLUSTER_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: sabnzbd-config
      nfs-video-media:
        enabled: true
        existingClaim: nfs-video-media
        mountPath: /mnt/storage/video
    podSecurityContext:
      supplementalGroups:
        - 100
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 7500Mi
