---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-music
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-music
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-video
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-video
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-downloads
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-downloads
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-photo
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-photo
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lychee-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lychee-uploads
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lychee-sym
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pyload-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flood-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-cache
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeName: qbittorrent-cache
  resources:
    requests:
      storage: 600Gi
