---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: bazarr
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: k8sathome/bazarr
      tag: v0.9.0.7
      pullPolicy: IfNotPresent
    env:
      TZ: "Europe/Paris"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config
    additionalVolumeMounts:
    - name: nfs-video
      mountPath: "/mnt/storage/video"
    additionalVolumes:
    - name: nfs-video
      persistentVolumeClaim:
        claimName: nfs-video
    resources:
      requests:
        memory: 500Mi
        cpu: 500m
      limits:
        memory: 1500Mi
  valuesFrom:
  - kind: ConfigMap
    name: helmrelease-media-bazarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 5Gi
