---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: jellyfin
      version: 7.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/jellyfin
      pullPolicy: IfNotPresent
      tag: bionic-10.7.1-1-ls16
    strategy:
      type: Recreate
    service:
      annotations:
        prometheus.io/probe: "true"
        prometheus.io/protocol: http
      port:
        port: 8096
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
    additionalVolumeMounts:
      - name: nfs-music
        mountPath: "/mnt/storage/music"
      - name: nfs-video
        mountPath: "/mnt/storage/video"
      - name: nfs-photo
        mountPath: "/mnt/storage/photo"
    additionalVolumes:
      - name: nfs-music
        persistentVolumeClaim:
          claimName: nfs-music
      - name: nfs-video
        persistentVolumeClaim:
          claimName: nfs-video
      - name: nfs-photo
        persistentVolumeClaim:
          claimName: nfs-photo
    resources:
      requests:
        memory: 4Gi
        cpu: 1
      limits:
        gpu.intel.com/i915: 1
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
        - host: jellyfin.k3s.xpander.ovh
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "jellyfin.k3s.xpander.ovh"
