---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lychee
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: lychee
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: lycheeorg/lychee-laravel
      pullPolicy: IfNotPresent
      tag: v4.0.8
    strategy:
      type: Recreate
    service:
      port:
        port: 80
      annotations:
        prometheus.io/probe: "true"
        prometheus.io/protocol: http
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    env:
      PHP_TZ: Europe/Paris
      DB_CONNECTION: postgresql
    persistence:
      config:
        enabled: true
        emptyDir: false
        mountPath: /conf
        existingClaim: lychee-config
      uploads:
        enabled: true
        emptyDir: false
        mountPath: /uploads
        existingClaim: lychee-uploads
      sym:
        enabled: true
        emptyDir: false
        mountPath: /sym
        existingClaim: lychee-sym
  valuesFrom:
  - kind: ConfigMap
    name: helmrelease-media-lychee
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lychee-config
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lychee-uploads
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lychee-sym
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 1Gi
