---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lychee
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: lychee
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: lycheeorg/lychee-laravel
      pullPolicy: IfNotPresent
      tag: v4.1.0
    strategy:
      type: Recreate
    service:
      port:
        port: 80
      annotations:
        prometheus.io/probe: "true"
        prometheus.io/protocol: http
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    env:
      PHP_TZ: Europe/Paris
      DB_CONNECTION: pgsql
    persistence:
      config:
        enabled: true
        mountPath: /conf
        existingClaim: lychee-config
      uploads:
        enabled: true
        mountPath: /uploads
        existingClaim: lychee-uploads
      sym:
        enabled: true
        mountPath: /sym
        existingClaim: lychee-sym
      photo:
        enabled: true
        mountPath: /mnt/storage/photo
        existingClaim: nfs-photo
  valuesFrom:
  - kind: ConfigMap
    name: helmrelease-media-lychee
