---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: navidrome
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: navidrome
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: deluan/navidrome
      pullPolicy: IfNotPresent
      tag: 0.40.0
    strategy:
      type: Recreate
    service:
      port:
        port: 4533
      annotations:
        prometheus.io/probe: "true"
        prometheus.io/protocol: http
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    env:
      ND_SCANINTERVAL: 15m
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_ENABLETRANSCODINGCONFIG: "true"
      ND_MUSICFOLDER: /mnt/storage/music/Artistes
    persistence:
      config:
        enabled: true
        mountPath: /conf
        existingClaim: navidrome-config
      music:
        enabled: true
        mountPath: /mnt/storage/music/
        existingClaim: nfs-music
  valuesFrom:
  - kind: ConfigMap
    name: helmrelease-media-navidrome
