---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pyload
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: pyload
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: linuxserver/pyload
      tag: version-5f5aaf56
      pullPolicy: IfNotPresent
    env:
      TZ: "Europe/Paris"
    persistence:
      config:
        enabled: true
        existingClaim: pyload-config
    additionalVolumeMounts:
    - name: nfs-downloads
      mountPath: "/mnt/storage/downloads"
    additionalVolumes:
    - name: nfs-downloads
      persistentVolumeClaim:
        claimName: nfs-downloads
    resources:
      requests:
        memory: 1Gi
        cpu: 100m
      limits:
        memory: 5Gi
    service:
      annotations:
        prometheus.io/probe: "true"
        prometheus.io/protocol: http
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - k3os-worker3
  valuesFrom:
  - kind: ConfigMap
    name: helmrelease-media-pyload
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pyload-config
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-backups
  resources:
    requests:
      storage: 1Gi