---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 9.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.3.3
      pullPolicy: IfNotPresent
    env:
      TZ: "Europe/Paris"
    service:
      additionalServices:
        - enabled: true
          nameSuffix: bittorrent
          type: LoadBalancer
          externalIPs:
            - 192.168.169.105
          port:
            port: 50413
            name: bittorrent
            protocol: TCP
            targetPort: 6881
          externalTrafficPolicy: Local
      service:
        annotations:
          prometheus.io/probe: "true"
          prometheus.io/protocol: tcp
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config
    additionalVolumeMounts:
      - name: qbittorrent-cache
        mountPath: "/downloads"
      - name: nfs-downloads
        mountPath: "/mnt/storage/downloads"
    additionalVolumes:
      - name: qbittorrent-cache
        persistentVolumeClaim:
          claimName: qbittorrent-cache
      - name: nfs-downloads
        persistentVolumeClaim:
          claimName: nfs-downloads
    resources:
      requests:
        memory: 4Gi
        cpu: 500m
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
        - host: qbittorrent.k3s.xpander.ovh
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "qbittorrent.k3s.xpander.ovh"
