---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 10.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.5.1143
      pullPolicy: IfNotPresent
    env:
      TZ: "Europe/Paris"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/auth-url: "http://authelia.auth.svc.cluster.local/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://login.k3s.xpander.ovh/"
      hosts:
        - host: sonarr.k3s.xpander.ovh
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "sonarr.k3s.xpander.ovh"
    additionalVolumeMounts:
      - name: nfs-video
        mountPath: "/mnt/storage/video"
      - name: qbittorrent-cache
        mountPath: "/downloads"
    additionalVolumes:
      - name: nfs-video
        persistentVolumeClaim:
          claimName: nfs-video
      - name: qbittorrent-cache
        persistentVolumeClaim:
          claimName: qbittorrent-cache
    resources:
      requests:
        memory: 500Mi
        cpu: 500m
      limits:
        memory: 1500Mi
    service:
      annotations:
        prometheus.io/probe: "true"
        prometheus.io/protocol: http
