---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: goldilocks
      version: 3.0.3
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
      interval: 5m
  values:
    vpa:
      enabled: true
    image:
      repository: quay.io/fairwinds/goldilocks
      tag: v3.0.0
    dashboard:
      replicaCount: 1
  valuesFrom:
  - kind: ConfigMap
    name: helmrelease-monitoring-goldilocks
