---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: healthchecks
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: healthchecks
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/healthchecks
      tag: v1.19.0-ls79
      pullPolicy: IfNotPresent

    controllerType: deployment

    strategy:
      type: Recreate

    resources: {}

    env:
      REGENERATE_SETTINGS: "True"
      EMAIL_USE_TLS: "True"
      ALLOWED_HOSTS: "*"
      DB: postgres

    service:
      port:
        port: 8000
      annotations:
        prometheus.io/probe: "true"
        prometheus.io/protocol: http

    nodeSelector: {}

    tolerations: []

    affinity: {}

    podAnnotations: {}

    persistence:
      config:
        enabled: false

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
        - host: healthchecks.k3s.xpander.ovh
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "healthchecks.k3s.xpander.ovh"

  valuesFrom:
    - kind: ConfigMap
      name: healthchecks-helmrelease
