apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:VqtitJcU71YOmjsFjqvDmHxhr9Zt/OuyziDuNMjmOhv49BaXquOMz1koM1BPPeOfaUkf8LXv+D/4FMA/HUxTwmWhJjzMn+HyY3S1LDeAZRaGm2Ox++Ww5VaSwezh7ORSnAbg3OSN2UGfF1x6IF8k19zx0Akk2+7yNWR5fMveip9Of6ad5ZQbYETKb5u18TLQFN/SZk1/CUB+5Ddhssz/tUlQIJXigWtWZh5zE8BdermsXQFtXFSjjjCVVo/08rE2ZBZCyIwJ0QnUCSnHj33AlI5YBEz7tAwNwdjwpihnb2Xokn/Mj52H7p0jR5A+YEJ3tPLPLT9hr+IHey3bOAbwfUwXVDKk87P8KkvrOCJN/PmNrMicbBABJG1pgDze,iv:EqHX+Xl4qT3lEStRKY4i3V6b6xB+j6pzaxm7sQLzQG4=,tag:WTe23jVwfACkesXu1sx6BQ==,type:str]
kind: ConfigMap
metadata:
    creationTimestamp: null
    name: helmrelease-media-lychee
    namespace: media
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-11T14:37:03Z'
    mac: ENC[AES256_GCM,data:8un+IEUmeI8Df868hb2FIFp1qVJ09hk7uKWBazcq7lxVoA822ulm+WkdJONVFlPxngvCn2cPZnHpbDESQwE6joKpFWswkw2JaGle4QKfopWTypUGk2gDzQra9p4f8IGJjbkPFv65E98DPV8VQch0XFhz1ZR7hq0MzYJnxoAtWlo=,iv:+4937BJEJKqPwdyhxfAJoCuQykDmky0OuAG6kqke7JY=,tag:SG8xFhRwhmcfzN0AbfdP8g==,type:str]
    pgp:
    -   created_at: '2020-12-11T14:37:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/JorPHm1g9XAQv/R93FR5j5XFSsFdjGF/EalzwR3EBMqkpEVMDWrCrZlTQu
            GCXrqhS8FVyjmkWTVwwvmRf2/aanbhCMPxseXrgz9dDWx7ncz8i567rvs1S/kcLi
            nbAKhwTtdVU/eP/twbLzF7gJacdCCkkk0eJ9k33+h5s88cbGxKniFKO3VEX/9tXX
            W8CjB5BtydaJ/GHCZc2HeG9CKIfA5pmYt2vyTgeIFap5HOf3VXQkuoSjhEkQ9QKO
            gdcvMJdH7vteo6WC1W42BN4S2vXIkjubbicCNKO3ymLgIBOl4k9Orj2yJBUtgDSJ
            csjXOnBhcnVAzsIlVux7cwH5VPjZckhJ0mIETluv+L6YQ2TZC0vIyfrN+iNvwuU+
            xnQJE1dTv/uHypBLfb9FcOn07gfmOtMk+At06trx4LcDTJ/wnVIPlDnPzUl4UslB
            Qqf/ZUgYetPubM88JyolqT8JN1POHtEmYc/US/LUMhbPBGhow9L/EcVAdM9sUTe1
            tY61+ONh+gup1f7ooXSA0l4Be3McMPazao4Xd1cK/8ilGECGFrOwROLR3BfDQMNJ
            3yJkbRTN2k15xNvXcfnCWQDx4iHywDzO0aCMM4BiEM0rbHKJjvRlwhY2FBVkxlQ+
            jqENAnFMhmZTETt9D3Rp
            =vgtn
            -----END PGP MESSAGE-----
        fp: C8F8A49D04A1AB639F8EA21CDBA4B1DCB1FA5BDD
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
