apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:wV5CDGWuUby2Rih+Hla9iupP5MXy6J8he1wpu0gb1Cmhr5CCzppwBtA/75+jTPeFiXKx9oBH1vMjrEl9KEz46wUwRaOl/BQII1Q6q29LEpoYeFLv3RlcP8z4fjQv0lAidjOwB3DGADZZ8BfT/dgRSOXs95jqn0DWvdarApXw5Iq3P4w2WiC4CdXHUqoNlBpiqQJFpk/DLSMngeTQjgz796GTK83iPhQjkxIvjFw0iiYK39lXcyTZAxIfXz0ye0mXH182L2/Fm+kj4jO0/32lU0u9VRmJoMiXFQQrveJFs/fX3xTXJY7jNFHzIOGjNMKDtr8=,iv:yyzLLrpKt1SHhIo+VycNTAymk4eEp/f27rSAhj/HCo0=,tag:6BjsG/BYjH3Xf5Gz9aJTcQ==,type:str]
kind: ConfigMap
metadata:
    name: helmrelease-media-flood
    namespace: media
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-08T02:44:34Z'
    mac: ENC[AES256_GCM,data:gaBuXR9XeQ8imRXrsgTSYLIP52wOT0FK9SdhC0II4Lggem0vC5gXI917YPoAcC262CmwHGg2DM4mLR8efL53EN1ks1fwhwor1mYobXGZdWKz+ALWJSbWSRNRMAiXsa/okDcVy1aMkaiDzxzp/2otI5s0TggpU5Zvs+vkZvZwxCE=,iv:X/pucICo6mxmA/wP1icpP3EQHwrS8K4L4kSwlRtswac=,tag:WVToyrn2fFQoebW7I0PSNw==,type:str]
    pgp:
    -   created_at: '2021-02-08T02:44:34Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/JorPHm1g9XAQv/UO7x9kzrpOpEboiI34VvNAaHbvULVRiUHptU/cjHwsZJ
            RaVTGioXWGFUJk3ZDRHJpI5JpTNX+68v8V/oIHkJGXux3GDHHTFAsHtMU74M9sHo
            osFf6jPCXzNdHE8O02B+QBUlr8f+cOwFRUlsozqHQEkGwOm4IVVQz0FFhFc1kgSJ
            U8CtbLL3gnxV+eS2PPZJOiaO8HkI7s9Em/zN00rRMM8yDpOk830wfT6oxaRX3bCs
            E/+P4VKneISqQXzCYe8R5VgQSbIQvmXrXwoebyxSFZAxTP/QhEbex/uwAyqRGGLX
            IIKHbV42WtANG3YAtayF7FDCtExn3Kh1X2SlM8OL89W5HI+gbAnG0ydxSu53ZX9O
            AgyETBZ2FQLzMyqcLJ2JR95uH5aXo6kmPwNi4Hic6EdUXl7zMXupbHT14MIoJUPc
            caFfAScnrVjY1OGfXqIkFvTgoQxAeCTiell7SiyWoIXlMlekl6f7pr/h+P/vLx1j
            bwlLU0I/C2qCXcOBSssa0l4B+1HfV/aYns3jsPXo48zGu/gLfRgqOKqg+ZkPLIf0
            gdzG6/z4eumVEZUC3uA7nGMj41xEQfgY8aB0S6cmxb993NiRnPRv7bLsJ8k9dI6e
            hpdRJqNbgY8gRBUaoLPB
            =Eryi
            -----END PGP MESSAGE-----
        fp: C8F8A49D04A1AB639F8EA21CDBA4B1DCB1FA5BDD
    encrypted_regex: ^(values.yaml|stringData)$
    version: 3.6.1
